---
title: "R Notebook"
output: html_notebook
---

### load the c++ log-likelihood function
```{r}
require(Rcpp)
require(BH)
Sys.setenv(CXX="/usr/local/bin/g++")
Sys.setenv("PKG_CXXFLAGS"="-std=c++11")
sourceCpp('../loglike_port_r.cpp')
```

### test the function
Benchmark from Matlab: -2484.01736459803 0.472533
```{r}
par = c(0.05, 2, 0.2, 0.25, -0.8, 0, 0, 0)
y = data.matrix(read.csv('YObs.csv', header = F))
start.time <- Sys.time()
loglike(par, y)
end.time <- Sys.time()
end.time - start.time
```

### use `nloptr` for mle 
```{r}
library(nloptr)
f <- function(p) {
    return(loglike(p, y))
}
opts <- list("algorithm"="NLOPT_LN_PRAXIS",
             "xtol_rel"=1.0e-7)
# set lower and upper bound
lb = c(0, 0, 0, 0, -0.95, 0, 0, 0)
ub = c(1, 5, 1, 1, 0.95, 0, 0, 0)
start.time <- Sys.time()
result = nloptr(x0 = c(0.1, 1, 0.1, 0.1, -0.5, 0, 0, 0), eval_f = f, 
       opts = opts, lb = lb, ub = ub)
end.time <- Sys.time()
print("estimator:")
print((result$solution)[1:5])
print("real parameters:")
print(par[1:5])
print("Optim Elapsed Time: ")
end.time - start.time
```


### Heston SVJ Simulation
Parameters:  
```{r}
library(ESGtoolkit)
# for implied volatility to option price
library(fOptions) 
V0 <- 0.1372
kappa <- 9.511/100
theta <- 0.0285
xi <- 0.801/100  #xi
rho <- -0.5483
lambda <- 0.3635
mu.J <- -0.2459
sigma.J <- 0.2547/100
m <- exp(mu.J + 0.5 * (sigma.J^2)) - 1
# Initial stock price
S0 <- 4468.17
# Initial short rate
r0 <- 0.0357
```
Simulation parameters:
```{r}
n <- 300 # of paths
freq <- "weekly"
horizon <- 1 # 1 year
```

Simulate shocks and volatility
```{r}
# Simulation of shocks, with antithetic variates
shocks <- simshocks(n = n, horizon = horizon, frequency = freq, method = "anti",
family = 1, par = rho)
# Vol simulation
sim.vol <- simdiff(n = n, horizon = horizon, frequency = freq, model = "CIR",
x0 = V0, theta1 = kappa * theta, theta2 = kappa, theta3 = xi, eps = shocks[[1]])
```

```{r}
esgplotts(sim.vol)
```

Simulate stock price
```{r}
# prices simulation
sim.price <- simdiff(n = n, horizon = horizon, frequency = freq, model = "GBM",
x0 = S0, theta1 = r0 - lambda * m, theta2 = sim.vol, lambda = lambda, mu.z = mu.J,
sigma.z = sigma.J, eps = shocks[[2]])
```

plot
```{r}
esgplotbands(sim.price, main = "with esgplotbands", xlab = "time", ylab = "values")
```

### Discounted Monte Carlo price:
T = 2 weeks
```{r}
as.numeric(esgmcprices(r0, sim.price, 2/52))
```

### Pricing of Option
```{r}
# Strike
K <- 3400
Kts <- ts(matrix(K, nrow(sim.price), ncol(sim.price)), start = start(sim.price),
deltat = deltat(sim.price), end = end(sim.price))
# Implied volatility
sigma.imp <- 0.6625
# Maturity
maturity <- 2/52
# payoff at maturity
payoff <- (sim.price - Kts) * (sim.price > Kts)
payoff <- window(payoff, start = deltat(sim.price), deltat = deltat(sim.price),
names = paste0("Series ", 1:n))
# True price
c0 <- GBSOption("c", S = S0, X = K, Time = maturity, r = r0, b = 0, sigma = sigma.imp)
c0@price
## [1] 1070
# Monte Carlo price
as.numeric(esgmcprices(r = r0, X = payoff, maturity))
## [1] 1063
# pct. difference
as.numeric((esgmcprices(r = r0, X = payoff, maturity = maturity)/c0@price -
1) * 100)
## [1] -0.6772
# Convergence towards the option price
esgmccv(r = r0, X = payoff, maturity = maturity, main = "Convergence towards the call \n option price")
```