---
title: "R Notebook"
output: html_notebook
---

### Heston SVJ 
simulate (y, v)

#### parameters 
```{r}
library(ESGtoolkit)
# for implied volatility to option price
library(fOptions) 
V0 <- 0.1372
kappa <- 9.511/100
theta <- 0.0285
xi <- 0.801/100  #xi
rho <- -0.5483
lambda <- 0.3635
mu.J <- -0.2459
sigma.J <- 0.2547/100
m <- exp(mu.J + 0.5 * (sigma.J^2)) - 1
# Initial stock price
S0 <- 4468.17
# Initial short rate
r0 <- 0.0357
par = c(r0, kappa, theta, xi, rho, lambda, mu.J, sigma.J^2)
```

```{r}
n <- 300 # of paths
freq <- "daily"
horizon <- 1 # 1 year
```

```{r}
# Simulation of shocks, with antithetic variates
shocks <- simshocks(n = n, horizon = horizon, frequency = freq, method = "anti",
family = 1, par = rho)
# Vol simulation
sim.vol <- simdiff(n = n, horizon = horizon, frequency = freq, model = "CIR",
x0 = V0, theta1 = kappa * theta, theta2 = kappa, theta3 = xi, eps = shocks[[1]])
# prices simulation
sim.price <- simdiff(n = n, horizon = horizon, frequency = freq, model = "GBM",
x0 = S0, theta1 = r0 - lambda * m, theta2 = sim.vol, lambda = lambda, mu.z = mu.J,
sigma.z = sigma.J, eps = shocks[[2]])

# select path path
path = 1
v = as.numeric(sim.vol[, path])
y <- log(as.numeric(sim.price[, path]))
```


```{r}
require(Rcpp)
require(BH)
Sys.setenv(CXX="/usr/local/bin/g++")
Sys.setenv("PKG_CXXFLAGS"="-std=c++11")
sourceCpp('../loglike_port_r.cpp')
```


```{r}
library(nloptr)
f <- function(p) {
    return(loglike(p, y))
}
opts <- list("algorithm"="NLOPT_GN_DIRECT_L", "xtol_rel"=1.0e-7)
             #NLOPT_LN_PRAXIS"
             
# set lower and upper bound
lb = c(0, 0, 0, 0, -1, 0, -1, 0)
ub = c(1, 0.1, 1, 1, 1, 0.5, 0, 0.01)
start.time <- Sys.time()
result = nloptr(x0 = c(0.02, 0.05, 0.03, 0.005, -0.04, 0.2, -0.2, 0.000002), eval_f = f, 
       opts = opts, lb = lb, ub = ub)
end.time <- Sys.time()
end.time - start.time
print(result$solution)
```