---
title: "R Notebook"
output: html_notebook
---

### Heston SVJ 
simulate (y, v)

#### parameters 
```{r}
library(ESGtoolkit)
kappa <- 2
theta <- 0.2
xi <- 0.25  
rho <- -0.8
lambda <- 0
mu.J <- -0
sigma.J <- 0
m <- exp(mu.J + 0.5 * (sigma.J^2)) - 1
# Initial stock price
S0 <- exp(4.60517018598809)
r0 <- 0.05
par = c(r0, kappa, theta, xi, rho, lambda, mu.J, sigma.J^2)
gamma_shape = 2*kappa*theta/xi^2
gamma_scale = theta/gamma_shape
V0 = rgamma(1, shape = gamma_shape, scale = gamma_scale)
```

```{r}
n <- 2 # of paths
freq <- "daily"
horizon <- 5 # 1 year
```

```{r}
# Simulation of shocks, with antithetic variates
shocks <- simshocks(n = n, horizon = horizon, frequency = freq, method = "anti",
family = 1, par = rho)
# Vol simulation
sim.vol <- simdiff(n = n, horizon = horizon, frequency = freq, model = "CIR",
x0 = V0, theta1 = kappa * theta, theta2 = kappa, theta3 = xi, eps = shocks[[1]])
# prices simulation
sim.price <- simdiff(n = n, horizon = horizon, frequency = freq, model = "GBM",
x0 = S0, theta1 = r0 - lambda * m, theta2 = sim.vol, lambda = lambda, mu.z = mu.J,
sigma.z = sigma.J, eps = shocks[[2]])

# select path path
path = 1
y <- log(as.numeric(sim.price[, path]))
YObs = y[261:1261]
y = YObs
write.csv(YObs, 'myYObs.csv', row.names = FALSE)
```


```{r}
require(Rcpp)
require(BH)
Sys.setenv(CXX="/usr/local/bin/g++")
Sys.setenv("PKG_CXXFLAGS"="-std=c++11")
sourceCpp('../loglike_port_r.cpp')
```


```{r}
library(nloptr)
f <- function(p) {
    return(loglike(p, y))
}
#local_opts <- list("algorithm"="NLOPT_LN_COBYLA", "xtol_rel"=1.0e-7) 
#opts <- list("algorithm"="NLOPT_GN_MLSL", "xtol_rel"=1.0e-7, local_opts = local_opts)
opts <- list("algorithm"="NLOPT_LN_COBYLA", "xtol_rel"=1.0e-4)

# set lower and upper bound
lb = c(-0.1, 0.1, 0.01, 0, -0.95, 0, 0, 0)
ub = c(0.1, 10, 1, 1, 0.95, 0, 0, 0)
start.time <- Sys.time()
result = nloptr(x0 = c(0.05, 2, 0.2, 0.25, -0.8, 0, 0, 0), eval_f = f, 
       opts = opts, 
       lb = lb, ub = ub)
end.time <- Sys.time()
end.time - start.time
print(result$solution)
```